# 1. Index
- [.set_index](https://trenton3983.github.io/files/projects/2019-02-04_manipulating_dataframes_with_pandas/2019-02-04_manipulating_dataframes_with_pandas.html#https://www.datacamp.com/courses/manipulating-dataframes-with-pandas)
- [.reset_index](https://www.datacamp.com/community/tutorials/pandas-tutorial-dataframe-python)
- [.reindex](https://campus.datacamp.com/courses/pandas-foundations/time-series-in-pandas?ex=5)
- (df.index=)  + (del col) 
  - **df=** df.set_index
  - df.set_index(**inplace=True**)
- pd.read_csv(**index_col=**)
- pd.Series(prices, **index=**)  


| methods  |   | 
|---|---|
|set_index   |drop/inplace| 
| reset_index  | drop/inplace  | 
|   |   |

## 1.1. Create df or series using index argument

In [2]:
import pandas as pd

In [3]:
prices = [10.70, 10.86, 10.74, 10.71, 10.79]
days = ['Mon', 'Tue', 'Wed', 'Thur', 'Fri']
shares = pd.Series(prices, index=days)
print(shares)

Mon     10.70
Tue     10.86
Wed     10.74
Thur    10.71
Fri     10.79
dtype: float64


## 1.2 Using read_csv
- index_col=
- df.index + del col

In [25]:
pd.read_csv('users.csv')

Unnamed: 0 weekday    city  visitors  signups
0           0     Sun  Austin       139        7
1           1     Sun  Dallas       237       12
2           2     Mon  Austin       326        3
3           3     Mon  Dallas       456        5

### 1.2.1 index_col=

In [60]:
users=pd.read_csv('users.csv',index_col='city')
users

Unnamed: 0 weekday  visitors  signups
city                                         
Austin           0     Sun       139        7
Dallas           1     Sun       237       12
Austin           2     Mon       326        3
Dallas           3     Mon       456        5

### 1.2.2 Assigning the index

In [35]:
users.index=users.weekday

In [36]:
users.head()   ## the prior index col disappear

Unnamed: 0 weekday  visitors  signups
weekday                                       
Sun               0     Sun       139        7
Sun               1     Sun       237       12
Mon               2     Mon       326        3
Mon               3     Mon       456        5

In [37]:
del users['weekday']   ## remove the col used as index by the assignment
users.head()

Unnamed: 0  visitors  signups
weekday                               
Sun               0       139        7
Sun               1       237       12
Mon               2       326        3
Mon               3       456        5

In [40]:
new_idx = [x.upper() for x in users.index]
users.index = new_idx
print(users)

     Unnamed: 0  visitors  signups
SUN           0       139        7
SUN           1       237       12
MON           2       326        3
MON           3       456        5


### 1.2.3 set_index - hierarchical indexing

In [49]:
stocks = pd.DataFrame([['2016-10-03', 31.50, 14070500, 'CSCO'],
                       ['2016-10-03', 112.52, 21701800, 'AAPL'],
                       ['2016-10-03', 57.42, 19189500, 'MSFT'],
                       ['2016-10-04', 113.00, 29736800, 'AAPL'],
                       ['2016-10-04', 57.24, 20085900, 'MSFT'],
                       ['2016-10-04', 31.35, 18460400, 'CSCO'],
                       ['2016-10-05', 57.64, 16726400, 'MSFT'],
                       ['2016-10-05', 31.59, 11808600, 'CSCO'],
                       ['2016-10-05', 113.05, 21453100, 'AAPL']],
                      columns=['Date', 'Close', 'Volume', 'Symbol'])
stocks

Date   Close    Volume Symbol
0  2016-10-03   31.50  14070500   CSCO
1  2016-10-03  112.52  21701800   AAPL
2  2016-10-03   57.42  19189500   MSFT
3  2016-10-04  113.00  29736800   AAPL
4  2016-10-04   57.24  20085900   MSFT
5  2016-10-04   31.35  18460400   CSCO
6  2016-10-05   57.64  16726400   MSFT
7  2016-10-05   31.59  11808600   CSCO
8  2016-10-05  113.05  21453100   AAPL

In [50]:
stocks1=stocks.set_index('Date')
stocks1

Close    Volume Symbol
Date                               
2016-10-03   31.50  14070500   CSCO
2016-10-03  112.52  21701800   AAPL
2016-10-03   57.42  19189500   MSFT
2016-10-04  113.00  29736800   AAPL
2016-10-04   57.24  20085900   MSFT
2016-10-04   31.35  18460400   CSCO
2016-10-05   57.64  16726400   MSFT
2016-10-05   31.59  11808600   CSCO
2016-10-05  113.05  21453100   AAPL

In [52]:
stocks.set_index('Date',inplace=True)
stocks

Close    Volume Symbol
Date                               
2016-10-03   31.50  14070500   CSCO
2016-10-03  112.52  21701800   AAPL
2016-10-03   57.42  19189500   MSFT
2016-10-04  113.00  29736800   AAPL
2016-10-04   57.24  20085900   MSFT
2016-10-04   31.35  18460400   CSCO
2016-10-05   57.64  16726400   MSFT
2016-10-05   31.59  11808600   CSCO
2016-10-05  113.05  21453100   AAPL

#### MultiIndex and pilot table

### 1.2.4 reset_index()

In [53]:
stocks.reset_index()

Date   Close    Volume Symbol
0  2016-10-03   31.50  14070500   CSCO
1  2016-10-03  112.52  21701800   AAPL
2  2016-10-03   57.42  19189500   MSFT
3  2016-10-04  113.00  29736800   AAPL
4  2016-10-04   57.24  20085900   MSFT
5  2016-10-04   31.35  18460400   CSCO
6  2016-10-05   57.64  16726400   MSFT
7  2016-10-05   31.59  11808600   CSCO
8  2016-10-05  113.05  21453100   AAPL

In [58]:
stocks.groupby('Symbol').sum()

Close    Volume
Symbol                  
AAPL    338.57  72891700
CSCO     94.44  44339500
MSFT    172.30  56001800

In [59]:
stocks.groupby('Symbol')['Close'].sum().rename('Total').reset_index()

Symbol   Total
0   AAPL  338.57
1   CSCO   94.44
2   MSFT  172.30

# [Arithmetic -broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/03.03-operations-in-pandas.html)

In [65]:
import numpy as np

rng = np.random.RandomState(42)

In [61]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [62]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [151]:
A = rng.randint(10, size=(4, 4))
A

array([[3, 5, 1, 9],
       [1, 9, 3, 7],
       [6, 8, 7, 4],
       [1, 4, 7, 9]])

In [144]:
A-A[0]

array([[ 0,  0,  0,  0],
       [-3,  3,  1, -3],
       [-6, -3,  6,  0],
       [-8,  1,  4,  6]])

In [140]:
row=A[0]

In [141]:
A.shape

(4, 4)

In [142]:
row.shape

(4,)

In [153]:
A[:,0]

array([3, 1, 6, 1])

In [152]:
A-A[:,0]

array([[ 0,  4, -5,  8],
       [-2,  8, -3,  6],
       [ 3,  7,  1,  3],
       [-2,  3,  1,  8]])

<font color='red'>In Pandas, the convention similarly operates row-wise by default:

In [164]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -2  4  2 -2
2  3  3  6 -5
3 -2 -1  6  0

In [184]:
df.iloc[:,0]

0    3
1    1
2    6
3    1
Name: Q, dtype: int32

In [80]:
df-df['Q']

Q   R   S   T   0   1   2   3
0 NaN NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN NaN

In [182]:
df.iloc[:,[1]]

R
0  5
1  9
2  8
3  4

In [173]:
df['Q']

0    3
1    1
2    6
3    1
Name: Q, dtype: int32

In [174]:
df-df['Q']

Q   R   S   T   0   1   2   3
0 NaN NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN NaN

In [149]:
df.subtract(df['Q'],axis=0)

Q  R  S  T
0  0 -5 -8 -6
1  0  1 -4 -6
2  0 -2  4  0
3  0  4  4  8

In [74]:
df = pd.DataFrame(A, columns=list('QRST'))
df - pd.Series([1,1,1,1])

Q   R   S   T   0   1   2   3
0 NaN NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN NaN

In [104]:
m=np.ones((2,3))

In [105]:
a=np.arange(3)

In [106]:
m

array([[1., 1., 1.],
       [1., 1., 1.]])

In [108]:
m+a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [154]:
a = np.arange(3)
a

array([0, 1, 2])

In [158]:
aT=a[:,np.newaxis]
aT

array([[0],
       [1],
       [2]])

In [156]:
aT.shape

(3, 1)

In [157]:
np.arange(3).reshape((3, 1))

array([[0],
       [1],
       [2]])

In [133]:
a

array([[0],
       [1],
       [2]])

In [134]:
b

array([0, 1, 2])

In [135]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [160]:
a=np.random.randint(0,3,3)
a

array([2, 1, 2])

In [129]:
a2=np.random.randint(0,3,(1,3))
a2

array([[1, 1, 2]])

In [131]:
a3=np.random.randint(0,3,(3,1))
a3

array([[2],
       [0],
       [0]])

In [161]:
a.T

array([2, 1, 2])

In [162]:
a2.T

array([[1],
       [1],
       [2]])

In [101]:
b[:,np.newaxis]

array([[0],
       [1],
       [2]])

In [ ]:
M = np.ones((3, 2))
a = np.arange(3)

In [176]:
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64