In [35]:
import numpy as np
import tensorflow as tf

In [33]:
from tensorflow import keras

# Working with matrix
- create matrix
- matrix operation
 - arithmetic
 - linalg
 - ml preceeding function

## Creating matrix
- tf.eye/fill
- tf.linalg.diag
- tf.random

- tf.convert_to_tensor

In [3]:
identity_matrix=tf.linalg.diag([1.0,1.0,1.0])

In [4]:
A=tf.fill([2,3],5.0)
B=tf.random.uniform([3,2])
C=tf.random.truncated_normal([3,2])
D=tf.convert_to_tensor(np.array([[1,2,3],[7,8,9],[11,12,14]]),dtype=tf.float32)

In [5]:
print(A,"\n\n",B,"\n\n",C,"\n\n",D)

tf.Tensor(
[[5. 5. 5.]
 [5. 5. 5.]], shape=(2, 3), dtype=float32) 

 tf.Tensor(
[[0.7014419  0.24136186]
 [0.9684737  0.78737736]
 [0.13487399 0.7978046 ]], shape=(3, 2), dtype=float32) 

 tf.Tensor(
[[ 0.99460506 -0.47536266]
 [-0.53932464  0.7361718 ]
 [ 1.0354092   0.8617259 ]], shape=(3, 2), dtype=float32) 

 tf.Tensor(
[[ 1.  2.  3.]
 [ 7.  8.  9.]
 [11. 12. 14.]], shape=(3, 3), dtype=float32)


## Matrix operature
- tf.matmul (dot_product)
- tf.multiply (element-wise multiplication)

In [6]:
print(C+B)

tf.Tensor(
[[ 1.696047   -0.2340008 ]
 [ 0.42914903  1.5235491 ]
 [ 1.1702832   1.6595305 ]], shape=(3, 2), dtype=float32)


In [ ]:
print(tf.matmul(A,identity_matrix))

In [7]:
print(tf.multiply(identity_matrix,D))

tf.Tensor(
[[ 1.  0.  0.]
 [ 0.  8.  0.]
 [ 0.  0. 14.]], shape=(3, 3), dtype=float32)


### Transpose

In [9]:
print(tf.transpose(C))

tf.Tensor(
[[ 0.99460506 -0.53932464  1.0354092 ]
 [-0.47536266  0.7361718   0.8617259 ]], shape=(2, 3), dtype=float32)


### Liner Algebra
- tf.linalg.det
- tf.linalg.inv
- tf.linalg.cholesky
- tf.linalg.eigh


In [12]:
print(tf.linalg.det(identity_matrix))

tf.Tensor(1.0, shape=(), dtype=float32)


In [13]:
print(tf.linalg.inv(identity_matrix))

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [14]:
print(tf.linalg.cholesky(identity_matrix))

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [15]:
print(np.linalg.eigh(identity_matrix))

(array([1., 1., 1.], dtype=float32), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32))


## Machine learning preceeding function to compose a DAA

In [21]:
def custom_polynomial(value):
    return tf.math.subtract(3*tf.math.square(value),(value))+10
print(custom_polynomial(11))

tf.Tensor(36862, shape=(), dtype=int32)


# Implementing activation function
- tf.nn
 - relu6
 - tanh
 - sigmoid
 - softsign
 - softplus

## ReLU

In [22]:
print(tf.nn.relu([-3,3,10]))

tf.Tensor([ 0  3 10], shape=(3,), dtype=int32)


In [23]:
print(tf.nn.relu6([-3,3,10]))

tf.Tensor([0 3 6], shape=(3,), dtype=int32)


## sigmoid

In [26]:
print(tf.nn.sigmoid([-3.,3.,10]))

tf.Tensor([0.04742587 0.95257413 0.9999546 ], shape=(3,), dtype=float32)


## hyper tangent

In [28]:
print(tf.nn.tanh([-3.,3.,10.]))

tf.Tensor([-0.9950547  0.9950547  1.       ], shape=(3,), dtype=float32)
