# Manipulate data
Numpy
- **New dataset:** np.concatenate
 - 有通用的 concatenate
 - 有专门的 vstack, hstack, dstack  (split)
 - 有极简的 r_, c_
 - array.append
-**Change dimensions/shape:** Reshape/ravel&flatten - 
-**Change shape of 2_D:** Reshape/split


DataFrame
- pd.concat&merge/df.join()  **(axis or keys)**
- stack&unstack+multiINdex
-**Visulization:** Pivot/melt



# 1. Update dataset/add new elements

## 1.1 np.concatenate and np.stack
**np.concatenate([],axis)** /np.append()/np.insert()/np.delete()  
**np.stack((),axis)** <font color='red'>no unstack use split</font>    
**np.split(array,[index],axis)**  

- np.vstack：v 代表 vertical，竖直合并，等价于 concatenate(axis=0)
- np.hstack：h 代表 horizontal，水平合并，等价于 concatenate(axis=1)
- np.dstack：d 代表 depth-wise，按深度合并，深度有点像彩色照片的 RGB 通道

---
- hsplit,   
- vsplit

[R1](https://jakevdp.github.io/PythonDataScienceHandbook/03.06-concat-and-append.html)

[R2](https://mp.weixin.qq.com/s?__biz=MzIzMjY0MjE1MA==&mid=2247486784&idx=1&sn=50a54067e9d596d4a03beb2b281167fb&chksm=e8908e49dfe7075f3cb3b1d5ef9b6ad149c63d3e33a8a42e503717ed09d82df7aa71e87c1eb1&scene=21#wechat_redirect)

[R3](https://mp.weixin.qq.com/s?__biz=MzIzMjY0MjE1MA==&mid=2247486547&idx=1&sn=b3e8816663938f55df8603990c5d42db&chksm=e8908f5adfe7064c8500716ac77e5579077ef186ce9721110cc06c26b11ba7a10b65ea82862a&scene=21#wechat_redirect)

In [2]:
import numpy as np

In [3]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [5]:
print(np.concatenate([arr1, arr2], axis=0))
print(np.concatenate([arr1, arr2], axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [6]:
print( np.vstack((arr1, arr2)) )
print( np.hstack((arr1, arr2)) )
print( np.dstack((arr1, arr2)) )

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


## 1.2 np.r_ and np.c_

1. 参数可以是切片。

In [15]:
print( np.r_[-2:2:1, [0]*3, 5, 6] )

[-2 -1  0  1  0  0  0  5  6]


2. 第一个参数可以是控制参数，如果它用 'r' 或 'c' 字符可生成线性代数最常用的 matrix (和二维 numpy array 稍微有些不同)

In [16]:
np.r_['r', [1,2,3], [4,5,6]]

matrix([[1, 2, 3, 4, 5, 6]])

In [17]:
np.r_['c', [1,2,3], [4,5,6]]

matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

3. 第一个参数可以是控制参数，如果它写成 ‘a,b,c’ 的形式，其中  
a：代表轴，按「轴 a」来合并  
b：合并后数组维度至少是 b  
c：在第 c 维上做维度提升  

In [19]:
print( np.r_['0,2,0', [1,2,3], [4,5,6]] )
print( np.r_['0,2,1', [1,2,3], [4,5,6]] )
print( np.r_['1,2,0', [1,2,3], [4,5,6]] )
print( np.r_['1,2,1', [1,2,3], [4,5,6]] )

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3 4 5 6]]


## 1.3 split
使用「分裂」函数有两种选择
- 有通用的 split -concatenate() 函数一样，我们可以在 split() 函数里通过设定轴，来对数组沿着竖直方向分裂 (轴 0) 和沿着水平方向分裂 (轴 1)
- 有专门的 hsplit, vsplit - vsplit() 和 split(axis=0) 等价，hsplit() 和 split(axis=1) 等价  

![](https://mmbiz.qpic.cn/mmbiz_png/e4kxNicDVcCGvrjj2ow2W5KGAYOEIaf4XebCO1AHJibicVZ0UibuOe3fFneM28CTbQW9l6TNowHGWvyR3XYU4o0Yrg/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1&wx_co=1)

In [10]:
arr = np.arange(25).reshape((5,5))
print( arr )
print()
first, second, third = np.split(arr,[1,3])
print( 'The first split is', first )
print( 'The second split is', second )
print( 'The third split is', third )

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

The first split is [[0 1 2 3 4]]
The second split is [[ 5  6  7  8  9]
 [10 11 12 13 14]]
The third split is [[15 16 17 18 19]
 [20 21 22 23 24]]


split() 默认沿着轴 0 分裂，其第二个参数 [1, 3] 相当于是个切片操作 **[where to cut @ row1 and row3]**，将数组分成三部分：



第一部分 - :1 (即第 1 行)

第二部分 - 1:3 (即第 2 到 3 行)

第二部分 - 3:  (即第 4 到 5 行)

In [11]:
first, second, third = np.hsplit(arr,[1,3])
print( 'The first split is', first )
print( 'The second split is', second )
print( 'The third split is', third )

The first split is [[ 0]
 [ 5]
 [10]
 [15]
 [20]]
The second split is [[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]
The third split is [[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]


In [14]:
first, second = np.hsplit(arr,[3])
print( 'The first split is', first )
print( 'The second split is', second )


The first split is [[ 0  1  2]
 [ 5  6  7]
 [10 11 12]
 [15 16 17]
 [20 21 22]]
The second split is [[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]
