# 1. How to represent a vector
- **1-d or 2-d?**

In [5]:
# row vector

import numpy as np
from scipy import linalg
a=np.array([1,2,3,4]) ## This gives us a row vector

# Convert to a column vector -- transpose doesn't work for 1d array
print(a)
print(a.transpose())

[1 2 3 4]
[1 2 3 4]


In [5]:
# column vector

a_t=a[:,np.newaxis]
a_t.shape

(4, 1)

## Vector as a 2-D matrix - np.array([[]])

In [7]:
## use transpose to create column vector...

A=np.array([[1,2,3,4]])
print(A)
column_vector=A.T
print(column_vector)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


# 2. Operation
- **dot product**
  - 1d/1d
  - 2d.T/2d

In [8]:
u=np.array([3,4,5])
v=np.array([1,4,7])
print(np.dot(u,v))

54


In [14]:
u=np.array([[3,4,5]])
v=np.array([[1,4,7]]).T
print(np.dot(u,v))


A=np.array([[1,2]
            ,[3,4]
            ,[5,6]
            ,[7,8]])
B=np.array([[2,3,4,5]
           ,[6,7,8,9]])
print(np.dot(A,B))

[[54]]
[[ 14  17  20  23]
 [ 30  37  44  51]
 [ 46  57  68  79]
 [ 62  77  92 107]]


### 2.1 Linear equations and solutions


In [3]:
u=np.array([[3,4,5]]).T
w=np.array([[7,8,9]]).T
v=np.array([[1,4,7]]).T

print(3*u+4*v+5*w)

[[48]
 [68]
 [88]]


In [8]:
A=np.array([[2,1],
            [1,2],
            [1,4]])
b=np.array([[4,3,9]]).T

A_T_A=np.dot(A.T,A)
x=np.dot(np.dot(linalg.inv(A_T_A),A.T),b)
print(x)

[[0.83870968]
 [1.87096774]]


## 3. Matrix-operation
- **Rank**
- **Inversed matrix**
- **Eigenvector**
- **Covariance matrix**
- **SVD**

In [15]:
print(np.linalg.matrix_rank(A))

2


In [10]:
A=np.array([[1,2],[2,3]])
A_n=linalg.inv(A)
print(A_n)

[[-3.  2.]
 [ 2. -1.]]


In [12]:
evalue,evector=linalg.eig(A)
print(evalue,evector)

[-0.23606798+0.j  4.23606798+0.j] [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [14]:

np.cov(A)

array([[0.5, 0.5],
       [0.5, 0.5]])

In [15]:
B=np.array([[2,1],
            [1,2],
            [1,4]])
U,sigma,VT=np.linalg.svd(B)